'use client';

import { useRef, useState } from 'react';
import classes from './image-picker.module.css';
import Image from 'next/image';

export default function ImagePicker({label , name }){
    const [pickedImage , setPickedImage] = useState();
    const imageInput = useRef();

    function HandlePickImage(){
        imageInput.current.click(); 
    }

    function handleImageChange(event){
        const file = event.target.files[0];

        if(!file){
            setPickedImage(null);
            return;
        }
        // now if we want to show that file on the UI we have to convert it into the so-called data URL , which is simply a value that can be used as an input for an image element so it can be used as source for the image element
        // we can do this with help of class built into js the file reader class
        const fileReader = new FileReader();

        // this function will be triggered once this readAsDataURL method is done but here we than won't get the generated URL  as an input 
        // instead of that we can access the URL by accessing fileReader.result
        fileReader.onload = ()=>{
            // that will give you the generated URL 
            setPickedImage(fileReader.result);
        }

        // this method doesn't actually return anything , not a promise , not the read file and it also doesn't take callback instead we can hold of that data URL  that's being generated by assigning a value to the on load property
        fileReader.readAsDataURL(file);
        
    }

    return (
        <div className={classes.picker}>
            <label htmlFor={name}>{label}</label>
            <div className={classes.controls}>
                <div className={classes.preview}>
                    {!pickedImage && <p>No image picked yet</p>}
                    {pickedImage && (
                        <Image 
                            src={pickedImage} 
                            alt='The image selected by user' 
                            fill 
                        />
                    )}
                </div>
                <input 
                    ref={imageInput}
                    className={classes.input}
                    type='file' 
                    id={name} 
                    accept='image/png , image/jpeg , image/jpg ' 
                    name={name} 
                    // you can allow user to pick multiple file by adding this 
                    // multiple
                    onChange={handleImageChange}
                    required
                />
                <button 
                    className={classes.button} 
                    type='button'
                    onClick={HandlePickImage}
                >
                    Pick an Image
                </button>
            </div>
        </div>
    )
}